### ISSUE TITLE
`mix ash_postgres.generate_migrations` errors out with `key :table not found in: nil`

### ISSUE THREAD

**Issue by bcksl** [ash-project/ash_postgres#140]
**Describe the bug**

Running `mix ash_postgres.generate_migrations` errors out with `key :table not found in: nil`.

The error:

```
Extension Migrations:
No extensions to install

Generating Tenant Migrations:

Generating Migrations:
** (KeyError) key :table not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
    (ash_postgres 1.3.19) lib/migration_generator/migration_generator.ex:129: anonymous fn/2 in AshPostgres.MigrationGenerator.find_references_primary_key/2
    (elixir 1.14.4) lib/enum.ex:4239: Enum.find_value_list/3
    (ash_postgres 1.3.19) lib/migration_generator/migration_generator.ex:109: anonymous fn/2 in AshPostgres.MigrationGenerator.add_references_primary_key/2
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ash_postgres 1.3.19) lib/migration_generator/migration_generator.ex:100: AshPostgres.MigrationGenerator.add_references_primary_key/2
    (ash_postgres 1.3.19) lib/migration_generator/migration_generator.ex:505: anonymous fn/2 in AshPostgres.MigrationGenerator.deduplicate_snapshots/4
    (elixir 1.14.4) lib/map.ex:258: Map.do_map/2
make: *** [migrations] Error 1
```

**To Reproduce**

Time permitting and necessity existing I will try to put together a minimal, let me know.

**Expected behavior**

Migrations will be generated happily.

**Runtime**

- Elixir 1.14.4
- Erlang/OTP 25 [erts-13.2]
- Ash* trunk

**Comment by zachdaniel** [comment]
Can you try main?

**Comment by zachdaniel** [comment]
Will close this, but comment/reopen if that doesn't fix it :)

**Comment by zachdaniel** [comment]
Wiping the new migrations generated recently or wiping all migrations?
