### ISSUE TITLE
Updating the latest Ash causes some queries to break

### ISSUE THREAD

**Issue by hanrelan** [ash-project/ash_postgres#161]
**Describe the bug**
after updating to the latest version of Ash, the following query doesn't work anymore:
```elixir
AudioFile |> Ash.Query.sort(index: :desc) |> Ash.Query.distinct(:visit_id) |>  read!(actor: user)
```
but changing it to:
```elixir
AudioFile |> Ash.Query.filter(user_id == ^user.id) |> Ash.Query.sort(index: :desc) |> Ash.Query.distinct(:visit_id) |>  read!(authorize?: false)
```
does seem to work (note I moved the `actor: user` on read into a user_id filter and set `authorize?: false`)

The error I'm getting is:
```
** (Ash.Error.Unknown) Unknown Error

* ** (Ecto.QueryError) could not find named binding `as(1)` in query:

from a0 in Scribble.Scribe.AudioFile,
  as: 0,
  join: a1 in subquery(from a0 in Scribble.Scribe.AudioFile,
  as: 0,
  join: u1 in Scribble.EmailHandler.User,
  on: a0.user_id == u1.id,
  where: type(u1.id, {:parameterized, Ash.Type.UUID.EctoType, []}) ==
  type(^..., {:parameterized, Ash.Type.UUID.EctoType, []}),
  where: type(a0.visit_id, {:parameterized, Ash.Type.UUID.EctoType, []}) in [
  type(^..., {:parameterized, Ash.Type.UUID.EctoType, []})
],
  order_by: [asc: fragment("? DESC", a0.index)],
  distinct: [asc: type(a0.visit_id, {:parameterized, Ash.Type.UUID.EctoType, []})],
  select: %{
  id:
    struct(a0, [
[truncated]
    ]).id,
  (elixir 1.15.4) lib/enum.ex:1819: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
  (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
  (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
  (ecto 3.10.3) lib/ecto/repo/queryable.ex:211: Ecto.Repo.Queryable.execute/4
  (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
  (ash_postgres 1.3.40) lib/data_layer.ex:673: AshPostgres.DataLayer.run_query/2
  (ash 2.13.3) lib/ash/actions/read.ex:2818: Ash.Actions.Read.run_query/6
  (ash 2.13.3) lib/ash/actions/read.ex:1391: anonymous fn/4 in Ash.Actions.Read.data_field/3
    (ash 2.13.3) lib/ash/error/error.ex:461: Ash.Error.choose_error/2
    (ash 2.13.3) lib/ash/error/error.ex:218: Ash.Error.to_error_class/2
    (ash 2.13.3) lib/ash/actions/read.ex:184: Ash.Actions.Read.do_run/3
    (ash 2.13.3) lib/ash/actions/read.ex:96: Ash.Actions.Read.run/3
    (ash 2.13.3) lib/ash/api/api.ex:1844: Ash.Api.read!/3
```
 
** Runtime
 - Elixir version: 1.15
 - Erlang version: 25
 - OS: Mac OS
 - Ash version: 2.13.3
 - any related extension versions
"ash_postgres": {:git, "https://github.com/ash-project/ash_postgres.git", "3d9a0cfb4f6748174bfa7396d4677b71f2556610", [branch: "main"]},
 
**Additional context**

**Comment by zachdaniel** [comment]
Can you try `main`? I believe I've fixed the issue :)

**Comment by hanrelan** [comment]
Seems to be fixed now - thanks!
