### ISSUE TITLE
Empty string in relationship converted to nil before save

### ISSUE THREAD

**Issue by moxley** [ash-project/ash_postgres#186]
**Describe the bug**

When updating a record that includes data for updating a relationship record, and the relationship data includes field with an empty string, a `nil` is swapped in for the empty string before persisting to Postgres.

**To Reproduce**

This example tries to update a parent and child record. In the child input data, there is a field named `text` that is being updated from `""` to the same value, `""`:

Parent resource
```elixir
defmodule GF.Groups.Group2 do
  use Ash.Resource, data_layer: AshPostgres.DataLayer
  alias GF.Groups.MembershipPlan

  postgres do
    table "groups"
    repo GF.Repo
  end

  actions do
    defaults [:read, :destroy]

    update :update do
      argument :membership_plans, {:array, :map}
      change manage_relationship(:membership_plans, type: :direct_control)
    end
  end

  relationships do
    has_many :membership_plans, MembershipPlan, destination_attribute: :group_id
  end
end
```

Child resource
```elixir
defmodule GF.Groups.MembershipPlan do
  use Ash.Resource, data_layer: AshPostgres.DataLayer

  postgres do
    table "membership_plans"
    repo GF.Repo
  end

  attributes do
    uuid_primary_key :id
    attribute :text, :string, default: ""
  end
end
```

Test:
```elixir
  test "membership_plans" do
      %{group: group} = ctx = AshFactory.with_group(%{})
      %{membership_plan: membership_plan} = AshFactory.with_membership_plan(ctx, text: "")

      membership_plans = [
        %{
          id: membership_plan.id,
          text: ""
        }
      ]

      group =
        group
        |> Ash.Changeset.for_update(:update, %{membership_plans: membership_plans},
          authorize?: false
        )
        |> GF.Ash.Api.update!()
  end
```

Add `dbg()` to ash_postgres/lib/data_layer.ex, `def update/2` (line ~1814):

```elixir
  @impl true
  def update(resource, changeset) do
    dbg(changeset)

    changeset.data
    |> Map.update!(:__meta__, &Map.put(&1, :source, table(resource, changeset)))
    |> ecto_changeset(changeset, :update)
    |> dbg()
    |> dynamic_repo(resource, changeset).update(
      repo_opts(changeset.timeout, changeset.tenant, changeset.resource)
    )
```

Test output:

```elixir
[lib/data_layer.ex:1335: AshPostgres.DataLayer.ecto_changeset/3]
changeset #=> #Ash.Changeset<
  api: GF.Ash.Api,
  action_type: :update,
  action: :update,
  attributes: %{text: nil},
  relationships: %{},
  errors: [],
  data: #GF.Groups.MembershipPlan<
    variants: #Ash.NotLoaded<:relationship>,
    __meta__: #Ecto.Schema.Metadata<:loaded, "membership_plans">,
    id: "a60a2174-ffc9-4946-b635-217589d24620",
    text: "",
    aggregates: %{},
    calculations: %{},
    __order__: nil,
    ...
  >,
  context: %{
    accessing_from: %{name: :membership_plans, source: GF.Groups.Group2},
    actor: nil,
    authorize?: false,
    changed?: true
  },
  valid?: true
>

[lib/data_layer.ex:1819: AshPostgres.DataLayer.update/2]
changeset.data #=> #GF.Groups.MembershipPlan<
  __meta__: #Ecto.Schema.Metadata<:loaded, "membership_plans">,
  id: "6174f1cd-8046-4c15-8292-f1d40e40eb11",
  text: "",
  aggregates: %{},
  calculations: %{},
  __order__: nil,
  ...
>
|> Map.update!(:__meta__, &Map.put(&1, :source, table(resource, changeset))) #=> #GF.Groups.MembershipPlan<
  variants: #Ash.NotLoaded<:relationship>,
  __meta__: #Ecto.Schema.Metadata<:loaded, "membership_plans">,
  id: "6174f1cd-8046-4c15-8292-f1d40e40eb11",
  text: "",
  aggregates: %{},
  calculations: %{},
  __order__: nil,
  ...
>
|> ecto_changeset(changeset, :update) #=> #Ecto.Changeset<
  action: nil,
  changes: %{text: nil},
  errors: [],
  data: #GF.Groups.MembershipPlan<>,
  valid?: true
>

  1) test update membership_plans (GF.Groups.Group2Test)
     test/gf/groups/group2_test.exs:152
     ** (Ash.Error.Unknown) Unknown Error
     
     * ** (Postgrex.Error) ERROR 23502 (not_null_violation) null value in column "text" of relation "membership_plans" violates not-null constraint
     
         table: membership_plans
         column: text
     
     Failing row contains (01ec9353-849c-488e-b13d-8485bf99231f, 15007, f, Plan 1, 0, 10.00, 6, null, f).
       (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto 3.10.3) lib/ecto/repo/schema.ex:764: Ecto.Repo.Schema.apply/4
       (ecto 3.10.3) lib/ecto/repo/schema.ex:467: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
       (ash_postgres 1.3.41) lib/data_layer.ex:1819: AshPostgres.DataLayer.update/2
       (ash 2.13.2) lib/ash/actions/update.ex:419: anonymous fn/6 in Ash.Actions.Update.as_requests/5
       (ash 2.13.2) lib/ash/changeset/changeset.ex:2093: Ash.Changeset.run_around_actions/2
       ...
```

**Expected behavior**

When there is an empty string in the input data, it should remain an empty string when writing to the database.

** Runtime
 - Elixir version: elixir 1.14.3-otp-25
 - Erlang version: erlang 25.2.2
 - OS: MacOS 14.1.1
 - Ash version 2.13.2
 - any related extension versions ash_postgres 1.3.41

**Additional context**

### Related bug 2

When directly updating the child resource (referenced above), not through a relationship, the return struct of the resource field is saved to the database as an empty string, but the field returned from the update as `nil`.

```elixir
      ctx = AshFactory.with_group(%{})
      %{membership_plan: plan} = AshFactory.with_membership_plan(ctx, text: "")

      attrs = %{
        id: plan.id,
        text: ""
      }

      plan =
        plan
        |> Ash.Changeset.for_update(:update, attrs, authorize?: false)
        |> GF.Ash.Api.update!()

plan #=> #GF.Groups.MembershipPlan<
  variants: #Ash.NotLoaded<:relationship>,
  __meta__: #Ecto.Schema.Metadata<:loaded, "membership_plans">,
  id: "2fa14be8-a936-41df-8159-7b6559850ee1",
  text: nil,
  aggregates: %{},
  calculations: %{},
  __order__: nil,
  ...
>
```

**Comment by moxley** [comment]
Turns out this is not a bug. Here's what I needed to do to fix this:

```elixir
defmodule GF.Groups.MembershipPlan do
  ...
  attributes do
    ...
    attribute :text, :string, default: "", constraints: [allow_empty?: true]
  end
```

`constraints: [allow_empty?: true]` is required to allow an empty string for this field.
