### ISSUE TITLE
Using expr_sort on an attribute of a relation gives a "Error while building reference"

### ISSUE THREAD

**Issue by jeroen11dijk** [ash-project/ash_postgres#216]
Using this read query on my dossiers table which has a has_one relation with details, I can sort the dossiers by their details.name using an aggregate.

```elixir

  aggregates do
    first :details_name, :details, :name
  end

    read :search_by_name_pagination do
      argument(:name_substring, :string, allow_nil?: false)
      argument(:sort_direction, :atom, allow_nil?: false, default: :asc)

      prepare build(
                load: [
                  :details,
                  events: [:event_type, treatment: [:provider], dossier: [:details]]
                ],
                sort: [details_name: arg(:sort_direction)]
              )

      pagination offset?: true, default_limit: 10

      filter(
        expr(
          contains(
            fragment("lower(?)", details.name),
            fragment("lower(?)", ^arg(:name_substring))
          )
        )
      )
    end
```

Yet when I try to use: ``sort: Ash.Sort.expr_sort(details.name, :string))`` Which I expect to work I get the following stacktrace:

```
** (exit) an exception was raised:
    ** (RuntimeError) Error while building reference: details.name
        (ash_postgres 1.4.0) lib/expr.ex:1575: AshPostgres.Expr.do_dynamic_expr/6
        (ash_postgres 1.4.0) lib/expr.ex:1186: AshPostgres.Expr.do_dynamic_expr/6
        (ash_postgres 1.4.0) lib/sort.ex:105: anonymous fn/5 in AshPostgres.Sort.sort/6
        (elixir 1.15.7) lib/enum.ex:4830: Enumerable.List.reduce/3
        (elixir 1.15.7) lib/enum.ex:2564: Enum.reduce_while/3
        (ash_postgres 1.4.0) lib/sort.ex:74: AshPostgres.Sort.sort/6
        (ash_postgres 1.4.0) lib/data_layer.ex:635: AshPostgres.DataLayer.return_query/2
        (ash 2.18.1) lib/ash/actions/read/read.ex:1465: anonymous fn/4 in Ash.Actions.Read.data_field/3
        (ash 2.18.1) lib/ash/engine/engine.ex:493: anonymous fn/2 in Ash.Engine.run_iteration/1
        (ash 2.18.1) lib/ash/engine/engine.ex:514: anonymous fn/4 in Ash.Engine.async/2
        (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
        (elixir 1.15.7) lib/task/supervised.ex:36: Task.Supervised.reply/4
        (ash 2.18.1) lib/ash/engine/engine.ex:508: Ash.Engine.async/2
        (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
        (ash 2.18.1) lib/ash/engine/engine.ex:658: Ash.Engine.start_pending_tasks/1
        (ash 2.18.1) lib/ash/engine/engine.ex:279: Ash.Engine.run_to_completion/1
        (ash 2.18.1) lib/ash/engine/engine.ex:208: Ash.Engine.do_run/2
        (ash 2.18.1) lib/ash/engine/engine.ex:104: Ash.Engine.run/2
        (ash 2.18.1) lib/ash/actions/read/read.ex:195: Ash.Actions.Read.do_run/3
        (ash 2.18.1) lib/ash/actions/read/read.ex:93: anonymous fn/3 in Ash.Actions.Read.run/3
```

**Comment by zachdaniel** [comment]
@jeroen11dijk would you mind trying this again against the latest version of `ash_postgres`? We made some changes that would tangibly affect this. If the issue persists, I'll take a look tomorrow.

**Comment by zachdaniel** [comment]
I'll close this for now, but please reopen if the issue persists after upgrading.
