### ISSUE TITLE
Incorrect validation error when using AshPostgres

### ISSUE THREAD

**Issue by albinkc** [ash-project/ash_postgres#243]
* creating new issue in case the original comment flies under the radar *

I'm getting a validation error, even though the status in the create response and DB says open (verified manually).

```elixir
  ticket = (  Helpdesk.Support.Ticket  |> Ash.Changeset.for_create(:open, %{subject: "My mouse won't click33!"})  |> Ash.create!())

22:09:03.164 [debug] QUERY OK db=2.4ms idle=1348.9ms
begin []

22:09:03.199 [debug] QUERY OK source="tickets" db=3.0ms
INSERT INTO "tickets" ("id","status","subject") VALUES ($1,$2,$3) RETURNING "status","subject","id" ["b201e6eb-f752-4f0d-b1d3-32013c47f8d0", :open, "My mouse won't click33!"]

22:09:03.204 [debug] QUERY OK db=2.1ms
commit []
#Helpdesk.Support.Ticket<
  __meta__: #Ecto.Schema.Metadata<:loaded, "tickets">,
  id: "b201e6eb-f752-4f0d-b1d3-32013c47f8d0",
  subject: "My mouse won't click33!",
  status: :open,
  aggregates: %{},
  calculations: %{},
  ...
>
iex(2)> ticket|> Ash.Changeset.for_update(:close)|> Ash.update!()
** (Ash.Error.Invalid) Invalid Error

* Invalid value provided for status: Ticket is already closed.

"closed"

  (elixir 1.16.2) lib/process.ex:860: Process.info/2
  (ash 3.0.0-rc.27) lib/ash/error/changes/invalid_attribute.ex:5: Ash.Error.Changes.InvalidAttribute.exception/1
  (ash 3.0.0-rc.27) lib/ash/query/function/error.ex:13: Ash.Query.Function.Error.evaluate/1
  (ash 3.0.0-rc.27) lib/ash/filter/runtime.ex:578: Ash.Filter.Runtime.resolve_expr/5
  (ash 3.0.0-rc.27) lib/ash/filter/runtime.ex:231: Ash.Filter.Runtime.do_match/5
  (ash 3.0.0-rc.27) lib/ash/changeset/changeset.ex:2203: anonymous fn/4 in Ash.Changeset.add_atomic_validations/3
  (elixir 1.16.2) lib/enum.ex:4839: Enumerable.List.reduce/3
  (elixir 1.16.2) lib/enum.ex:2582: Enum.reduce_while/3
    (elixir 1.16.2) lib/process.ex:860: Process.info/2
    (ash 3.0.0-rc.27) lib/ash/error/invalid.ex:5: Ash.Error.Invalid.exception/1
    (ash 3.0.0-rc.27) /Users/albin/projects/helpdesk/deps/splode/lib/splode.ex:211: Ash.Error.to_class/2
    (ash 3.0.0-rc.27) lib/ash/error/error.ex:33: Ash.Error.to_error_class/2
    (ash 3.0.0-rc.27) lib/ash/actions/update/bulk.ex:111: Ash.Actions.Update.Bulk.run/6
    (ash 3.0.0-rc.27) lib/ash/actions/update/update.ex:121: Ash.Actions.Update.run/4
    (ash 3.0.0-rc.27) lib/ash.ex:2351: Ash.update/2
    iex:2: (file)
```
My repo with the added extension and migrations: 
https://github.com/albinkc/helpdesk/

Not sure if I missed something

Ref: #242

_Originally posted by @albinkc in https://github.com/ash-project/ash_postgres/issues/242#issuecomment-2070268489_

**Comment by zachdaniel** [comment]
🤔 interesting. So, the reason this is failing is because `attribute_does_not_equal` is not validating the *existing* value, but rather the *new or existing* value. Although, I see now that your validation is happening before the change, and so this actually *should* work...will look into this presently. This may be a quirk of the new atomics system that isn't being handled properly. Thanks for the detailed report.
