### ISSUE TITLE
Regression installing ash_uuid extension

### ISSUE THREAD

**Issue by pinetops** [ash-project/ash_postgres#274]
With no migrations created, generate_migrations causes the following on rc.15:

```
** (FunctionClauseError) no function clause matching in AshUUID.PostgresExtension.install/1

    The following arguments were given to AshUUID.PostgresExtension.install/1:

        # 1
        0

    Attempted function clauses (showing 1 out of 1):

        def install(1)

    (ash_uuid 0.8.0-rc.1) lib/ash_uuid/postgres_extension.ex:7: AshUUID.PostgresExtension.install/1
    (elixir 1.16.2) lib/enum.ex:1801: anonymous fn/2 in Enum.map_join/3
    (elixir 1.16.2) lib/enum.ex:4378: Enum.map_intersperse_list/3
    (elixir 1.16.2) lib/enum.ex:4381: Enum.map_intersperse_list/3
    (elixir 1.16.2) lib/enum.ex:1801: Enum.map_join/3
    (ash_postgres 2.0.0-rc.15) lib/migration_generator/migration_generator.ex:248: anonymous fn/2 in AshPostgres.MigrationGenerator.create_extension_migrations/2
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (ash_postgres 2.0.0-rc.15) lib/migration_generator/migration_generator.ex:51: AshPostgres.MigrationGenerator.generate/2
```

Reverting to rc.14 fixes it.

Perhaps this?
https://github.com/ash-project/ash_postgres/commit/3334999eb1c2a9e6286d1bfa67dc82d76dba127a

**Comment by zachdaniel** [comment]
We fixed a bug with the migration generator in ash_postgres. What it was *supposed* to be doing was passing in the version that was installed before, so you can generate the smallest set of changes necessary. Instead it was always passing the latest migration number. Please open an issue on the library in question and point them at this explanation.
