### ISSUE TITLE
Can’t rollback only 1 migration ago with `mix ash.rollback`

### ISSUE THREAD

**Issue by legrec14** [ash-project/ash_postgres#298]
**Describe the bug**
Here is the first output of the command `mix ash.rollback`:
```Elixir
Getting extensions in current project...
Running rollback for AshPostgres.DataLayer...
How many migrations should be rolled back? (default: 0)

Last 20 migration names, with the input you must provide to
rollback up to *and including* that migration:

1: /20240522074714_migrate_to_ash.exs
2: /20240522074712_install_ash-functions_extension_3.exs
3: /20240423224527_rename_all_uuid_to_id.exs
[…]
```
It says default to 0.
If I populate "Rollback to:" with 0, nothing happens
But if I populate "Rollback to:" with 1, It rollbacks 2 migrations ago
If I populate "Rollback to:" with 2, It rollbacks 3 migrations ago
Etc…
So it seems I cannot rollback just 1 migration ago with that command

**To Reproduce**
Just try to rollback 1 migration ago on a project.

**Expected behavior**
Be able to rollback 1 migration ago (as for instance with `mix ecto.rollback`).

** Runtime
 - Elixir version: 1.16
 - Erlang version: 26
 - OS: NixOS 23.11
 - Ash version: 3.0
 - any related extension versions: ash_postgres 2.0

**Additional context**
Nothing more to say.

**Comment by suciptoid** [comment]
1. After upgrade to ash_postgres: 2.0.8 the rollback list not shown:
```
Getting extensions in current project...
Running rollback for AshPostgres.DataLayer...

12:42:24.922 [debug] QUERY OK source="schema_migrations" db=1.9ms decode=4.4ms queue=75.2ms idle=0.0ms
SELECT s0."version" FROM "schema_migrations" AS s0 []
↳ anonymous fn/3 in AshPostgres.DataLayer.rollback/1, at: lib/data_layer.ex:440
How many migrations should be rolled back? (default: 0)

Last 20 migration names, with the input you must provide to
rollback up to *and including* that migration:


Rollback to: 
```
2. And after enter value 1, got error message:

```

** (UndefinedFunctionError) function MyApp.Repo.list_tenants/0 is undefined or private. Did you mean:

      * all_tenants/0

    (bundar 0.1.0) MyApp.Repo.list_tenants()
    (ash_postgres 2.0.6) lib/data_layer.ex:487: anonymous fn/3 in AshPostgres.DataLayer.rollback/1
    (ecto_sql 3.11.2) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
    (ash_postgres 2.0.6) lib/data_layer.ex:425: anonymous fn/3 in AshPostgres.DataLayer.rollback/1
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (mix 1.16.2) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.16.2) lib/mix/cli.ex:96: Mix.CLI.run_task/2
```

For problem no. 1 it's can be fixed with this diff:
```diff

--- a/lib/data_layer.ex
+++ b/lib/data_layer.ex
@@ -446,11 +446,11 @@ defmodule AshPostgres.DataLayer do
             |> Path.wildcard()
             |> Enum.sort()
             |> Enum.reverse()
+            |> Enum.map(&String.trim_leading(&1, migrations_path <> "/"))
             |> Enum.filter(fn file ->
               Enum.any?(current_migrations, &String.starts_with?(file, &1))
             end)
             |> Enum.take(20)
-            |> Enum.map(&String.trim_leading(&1, migrations_path))
             |> Enum.with_index()
             |> Enum.map(fn {file, index} -> "#{index + 1}: #{file}" end)
```

for problem no.2 i can't find docs about `Repo.list_tenants/0` function

**Comment by zachdaniel** [comment]
@suciptoid thank you for the report. These issues are now fixed in `main`.
