### ISSUE TITLE
Error thrown if relationship aggregate is used in update with atomic_update

### ISSUE THREAD

**Issue by TimisRobert** [ash-project/ash_postgres#311]
**Describe the bug**
 As discussed on Discord, I'm opening an issue to keep track of this.

**To Reproduce**
```elixir
defmodule Domain do
  use Ash.Domain

  resources do
    resource One
    resource Two
    resource Three
  end
end

defmodule One do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    domain: Domain

  attributes do
    uuid_primary_key :id
    attribute :quantity, :integer
  end
end

defmodule Two do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    domain: Domain

  attributes do
    uuid_primary_key :id
  end

  relationships do
    has_many :one, One
  end

  aggregates do
    sum :total_quantity, :one, :quantity, default: 0
  end
end

defmodule Three do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    domain: Domain

  attributes do
    uuid_primary_key :id
    attribute :total_quantity, :integer
  end

  relationships do
    belongs_to :two, Two
  end

  actions do
    update :update do
      require_atomic? false

      change atomic_update(:total_quantity, expr(two.total_quantity))
    end
  end
end
```

**Expected behavior**
To not throw

**Runtime**
 - Elixir version 1.16
 - Erlang version Erlang/OTP 26 [erts-14.2.5]
 - OS NixOS
 - Ash version main branch
 - any related extension versions

**Additional context**
```
** (KeyError) key :actor not found in: %{}
    (ash_sql 0.2.0) lib/aggregate.ex:723: anonymous fn/5 in AshSql.Aggregate.maybe_filter_subquery/6
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
    (ash_sql 0.2.0) lib/aggregate.ex:312: anonymous fn/10 in AshSql.Aggregate.add_aggregates/6
    (ash_sql 0.2.0) lib/join.ex:250: AshSql.Join.related_subquery/3
    (ash_sql 0.2.0) lib/aggregate.ex:159: anonymous fn/7 in AshSql.Aggregate.add_aggregates/6
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
    (ash_sql 0.2.0) lib/aggregate.ex:88: AshSql.Aggregate.add_aggregates/6
    (ash_sql 0.2.0) lib/join.ex:151: anonymous fn/10 in AshSql.Join.join_all_relationships/10
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
    (ash_postgres 2.0.6) lib/data_layer.ex:1441: anonymous fn/3 in AshPostgres.DataLayer.bulk_updatable_query/6
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
    (ash_postgres 2.0.6) lib/data_layer.ex:1436: AshPostgres.DataLayer.bulk_updatable_query/6
    (ash_postgres 2.0.6) lib/data_layer.ex:2671: AshPostgres.DataLayer.update/2
    (ash 3.0.8) lib/ash/actions/update/bulk.ex:2046: anonymous fn/5 in Ash.Actions.Update.Bulk.run_batch/10
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
```

**Comment by zachdaniel** [comment]
So I've added a test that replicates this pretty accurately as far as I can tell @TimisRobert, and it passes with recent changes made to `ash_postgres`. Please confirm one more time for me (previous confirmation was in discord) that updating `ash_postgres` to `main` does not resolve the issue. If you're already on main, make sure to do `mix deps.update ash_postgres` to make it point to the latest hash.

**Comment by TimisRobert** [comment]
I'm sure I have the latest, HEAD points to bc46d9d9c4b01cef85a553c2423ea2ddd2c5684e. It throws the same error still.

**Comment by zachdaniel** [comment]
@TimisRobert if you have some time to create a reproduction project using the latest `ash_postgres` release that would be amazing. Even better would be a test in the `ash_postgres` test suite. As far as I can tell, I've replicated as much of the scenario as I could and was unable to trigger the error. This may just be an issue on my end of course. I will close this for now until we can get it reliably reproduced so I can fix.
