### ISSUE TITLE
Table with same name in a different schema prevents resource generation.

### ISSUE THREAD

**Issue by bstime-tol** [ash-project/ash_postgres#386]
**Describe the bug**
See the 'To Reproduce section below'. In that case, the following stack trace is thrown

** (Postgrex.Error) ERROR 21000 (cardinality_violation) more than one row returned by a subquery used as an expression
    (ecto_sql 3.12.0) lib/ecto/adapters/sql.ex:1078: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ash_postgres 2.4.0) lib/resource_generator/spec.ex:990: anonymous fn/2 in AshPostgres.ResourceGenerator.Spec.table_specs/2
    (elixir 1.17.2) lib/enum.ex:4353: Enum.flat_map_list/2
    (ash_postgres 2.4.0) lib/resource_generator/spec.ex:88: anonymous fn/2 in AshPostgres.ResourceGenerator.Spec.tables/2
    (ecto_sql 3.12.0) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
    (ash_postgres 2.4.0) lib/resource_generator/spec.ex:86: AshPostgres.ResourceGenerator.Spec.tables/2
    (elixir 1.17.2) lib/enum.ex:4353: Enum.flat_map_list/2
    (ash_postgres 2.4.0) lib/resource_generator/resource_generator.ex:20: AshPostgres.ResourceGenerator.generate/4

**To Reproduce**
Create a database with multiple schemas. Create two tables with the same name but in differing schemas. E.g., auth.users and public.users.

Attempt to generate resource definitions:
```
mix ash_postgres.gen.resources MyApp.Auth --tables auth.users
```

**Expected behavior**
The resource generator successfully proposes code modifications.

** Runtime
 - Ash version 2.4.0

**Additional context**
The subquery here isn't constrained/scoped by schema: https://github.com/ash-project/ash_postgres/blob/d7a8083ff95081ba074eaf8b128e5d3a05148646/lib/resource_generator/spec.ex#L1012

**Comment by zachdaniel** [comment]
Thanks for the report! Fixed in `eb3329b4f300203aff2bc7302f72f85a947de489`

If you get the chance try it out. You can update your dependency to this `{:ash_postgres, github: "ash-project/ash"}` to pull from GitHub, and run the command again.
