### ISSUE TITLE
RuntimeError when using no_attributes? true relationships in filter expr

### ISSUE THREAD

**Issue by rapidfsub** [ash-project/ash_postgres#413]
**Describe the bug**
This issue is fixed.
https://github.com/ash-project/ash_postgres/issues/412

But still a bug is remaining.
When I use the relationship in filter expr, a RuntimeError occurs.

The three read actions below should be equivalent, I think.
But, only `list_by_store_id` works, and `list_by_store_id_alt1`, `list_by_store_id_alt2` don't work and raise error.

- actions in resource
```
defmodule SonetLib.SevenEleven.Product do
  actions do
    defaults [:read, create: :*]

    read :list_by_store_id do
      argument :store_id, :string, allow_nil?: false
      filter expr(stores.id == ^arg(:store_id))
    end

    read :list_by_store_id_alt1 do
      argument :store_id, :string, allow_nil?: false
      filter expr(stores_alt1.id == ^arg(:store_id))
    end

    read :list_by_store_id_alt2 do
      argument :store_id, :string, allow_nil?: false
      filter expr(stores_alt2.id == ^arg(:store_id))
    end

    update :purchase
  end
end
```

- stacktrace
```
  1) test relationships stores (SonetLib.SevenEleven.ProductTest)
     test/sonet_lib/seven_eleven/product_test.exs:25
     ** (RuntimeError) Error while building reference: inventories.store_id
     stacktrace:
       (ash_sql 0.2.37) lib/expr.ex:1796: AshSql.Expr.default_dynamic_expr/6
       (ash_sql 0.2.37) lib/expr.ex:909: AshSql.Expr.default_dynamic_expr/6
       (ash_sql 0.2.37) lib/filter.ex:37: anonymous fn/2 in AshSql.Filter.add_filter_expression/2
       (elixir 1.17.0) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ash_postgres 2.4.11) lib/data_layer.ex:2998: AshPostgres.DataLayer.filter/4
       (ash 3.4.36) lib/ash/query/query.ex:3106: Ash.Query.maybe_filter/3
       (ash 3.4.36) lib/ash/query/query.ex:2977: Ash.Query.data_layer_query/2
       (ash_sql 0.2.37) lib/join.ex:439: AshSql.Join.related_query/3
       (ash_sql 0.2.37) lib/join.ex:345: AshSql.Join.related_subquery/3
       (ash_sql 0.2.37) lib/join.ex:873: AshSql.Join.join_relationship/8
       (ash_sql 0.2.37) lib/join.ex:136: anonymous fn/10 in AshSql.Join.join_all_relationships/10
       (elixir 1.17.0) lib/enum.ex:4858: Enumerable.List.reduce/3
       (elixir 1.17.0) lib/enum.ex:2585: Enum.reduce_while/3
       (ash_postgres 2.4.11) lib/data_layer.ex:2991: AshPostgres.DataLayer.filter/4
       (ash 3.4.36) lib/ash/query/query.ex:3106: Ash.Query.maybe_filter/3
       (ash 3.4.36) lib/ash/query/query.ex:2977: Ash.Query.data_layer_query/2
       (ash 3.4.36) lib/ash/actions/read/read.ex:544: anonymous fn/8 in Ash.Actions.Read.do_read/5
       (ash 3.4.36) lib/ash/actions/read/read.ex:890: Ash.Actions.Read.maybe_in_transaction/3
       (ash 3.4.36) lib/ash/actions/read/read.ex:273: Ash.Actions.Read.do_run/3
       (ash 3.4.36) lib/ash/actions/read/read.ex:81: anonymous fn/3 in Ash.Actions.Read.run/3
```

**To Reproduce**
This is the test code to reproduce in my public repo.
https://github.com/rapidfsub/sonet/blob/develop/test/sonet_lib/seven_eleven/product_test.exs#L25

**Expected behavior**
No error raises, when using relationship in expr.

** Runtime
 - Elixir version
1.17.0-otp-27
 - Erlang version
27.0
 - OS
mac os sequoia
 - Ash version
git ref ee9415e7bff74210c1e4c3395dc619318a8eee47
 - any related extension versions
ash_postgres git ref 0e336d56e1091beec15d6f9173f5067e0a0f9271

**Additional context**

**Comment by zachdaniel** [comment]
Fixed in `ash_sql`. With that said, the queries it's generating in this case are not great. You may want to look into the guide on manual relationships and implementing this yourself if you have any performance issues. This is something we can eventually improve as an optimization.

**Comment by rapidfsub** [comment]
@zachdaniel Thanks for fix and advice.
But in this case, I want to use those relationships with no_attributes? true in "ash expression". (for filtering purpose)
I'll remember that the query would be not great.
