### ISSUE TITLE
Ash.count suddenly ignores tenant

### ISSUE THREAD

**Issue by DGollings** [ash-project/ash_postgres#440]
updated Ash recently (currently investigating which version broke it) but it keeps asking for a tenant, even though the tenant was already filled in (and still is)

```diff
-  "ash_postgres": {:hex, :ash_postgres, "2.4.15", "300768bfdf532b6a0af893a3688d73a708e6522730d9c1e61d4c837da0a62d6f", [:mix], [{:ash, ">= 3.4.44 and < 4.0.0-0", [hex: :ash, repo: "hexpm", optional: false]}, {:ash_sql, ">= 0.2.40 and < 1.0.0-0", [hex: :ash_sql, repo: "hexpm", optional: false]}, {:ecto, ">= 3.12.1 and < 4.0.0-0", [hex: :ecto, repo: "hexpm", optional: false]}, {:ecto_sql, "~> 3.12", [hex: :ecto_sql, repo: "hexpm", optional: false]}, {:igniter, ">= 0.4.4 and < 1.0.0-0", [hex: :igniter, repo: "hexpm", optional: false]}, {:inflex, "~> 2.1", [hex: :inflex, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: false]}, {:owl, "~> 0.11", [hex: :owl, repo: "hexpm", optional: false]}, {:postgrex, ">= 0.0.0", [hex: :postgrex, repo: "hexpm", optional: false]}], "hexpm", "ee4adf7f29647e27a49fcdfd51085b3539a7442794cabfb7841c4ee1fbb47a08"},
-  "ash_sql": {:hex, :ash_sql, "0.2.40", "b44a2b4a90e6bd228e60f673bc325e0c38bb0d94c2f36edfb45fb7d9bb418794", [:mix], [{:ash, ">= 3.1.7 and < 4.0.0-0", [hex: :ash, repo: "hexpm", optional: false]}, {:ecto, "~> 3.9", [hex: :ecto, repo: "hexpm", optional: false]}, {:ecto_sql, "~> 3.9", [hex: :ecto_sql, repo: "hexpm", optional: false]}], "hexpm", "a547a79a4d8ba84c2d8bb40aafbeddb0ad936987452d1612379e9c5f60b62747"},
+  "ash_postgres": {:hex, :ash_postgres, "2.4.14", "a7f352b65abddb8db3b6a49e09d040a6b960facd56e7037785a35bdeee7fed4a", [:mix], [{:ash, ">= 3.4.37 and < 4.0.0-0", [hex: :ash, repo: "hexpm", optional: false]}, {:ash_sql, ">= 0.2.39 and < 1.0.0-0", [hex: :ash_sql, repo: "hexpm", optional: false]}, {:ecto, ">= 3.12.1 and < 4.0.0-0", [hex: :ecto, repo: "hexpm", optional: false]}, {:ecto_sql, "~> 3.12", [hex: :ecto_sql, repo: "hexpm", optional: false]}, {:igniter, ">= 0.4.4 and < 1.0.0-0", [hex: :igniter, repo: "hexpm", optional: false]}, {:inflex, "~> 2.1", [hex: :inflex, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: false]}, {:owl, "~> 0.11", [hex: :owl, repo: "hexpm", optional: false]}, {:postgrex, ">= 0.0.0", [hex: :postgrex, repo: "hexpm", optional: false]}], "hexpm", "733eb85a8dee5c3a23d3816f26e3d19e2d35b8cd8241b6de4ad17be5b8495a37"},
+  "ash_sql": {:hex, :ash_sql, "0.2.39", "75411bea310ce514c16acd0855bdb9a754dba838fa566e1f053591fbd3da0dfb", [:mix], [{:ash, ">= 3.1.7 and < 4.0.0-0", [hex: :ash, repo: "hexpm", optional: false]}, {:ecto, "~> 3.9", [hex: :ecto, repo: "hexpm", optional: false]}, {:ecto_sql, "~> 3.9", [hex: :ecto_sql, repo: "hexpm", optional: false]}], "hexpm", "012904de597b9132b7dfdaf073ed8b0897f78ff9263f4036478cece4ac1fa97f"}
```

one of these deps broke this

How to reproduce, try to Ash.count anything on a resource that has tenancy enabled

```elixir
Foo
  |> Ash.count(tenant: input.tenant)
  ```

returns a `TenantRequired` error, even though its _right there_ :)

**Comment by zachdaniel** [comment]
Lets confirm a few things:

- its only those two packages that changed, right? No other packages?
- can you show the full stacktrace as well?

**Comment by DGollings** [comment]
1. that's the diff from the revert and it worked afterwards

2. sure

```elixir
 ** (Ash.Error.Unknown) 
 Bread Crumbs:
   > Exception raised in: MyApp.Planner.Route.create

 Unknown Error

 * ** (FunctionClauseError) no function clause matching in anonymous fn/1 in MyApp.Planner.Resources.Change.IncrementDailyRoute.change/3
   (myapp 0.1.0) anonymous fn({:error, %Ash.Error.Invalid{errors: [%Ash.Error.Invalid.TenantRequired{resource: MyApp.Planner.Route, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :invalid}]}}) in MyApp.Planner.Resources.Change.IncrementDailyRoute.change/3
   (myapp 0.1.0) lib/myapp/planner/resources/change/increment_daily_route.ex:25: anonymous fn/2 in MyApp.Planner.Resources.Change.IncrementDailyRoute.change/3
   (ash 3.4.44) lib/ash/changeset/changeset.ex:3836: anonymous fn/2 in Ash.Changeset.run_before_actions/1
   (elixir 1.17.3) lib/enum.ex:4858: Enumerable.List.reduce/3
   (elixir 1.17.3) lib/enum.ex:2585: Enum.reduce_while/3
   (ash 3.4.44) lib/ash/changeset/changeset.ex:3811: Ash.Changeset.run_before_actions/1
   (ash 3.4.44) lib/ash/changeset/changeset.ex:3950: Ash.Changeset.run_around_actions/2
   (ash 3.4.44) lib/ash/changeset/changeset.ex:3500: anonymous fn/3 in Ash.Changeset.with_hooks/3
   (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1400: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
   (db_connection 2.7.0) lib/db_connection.ex:1756: DBConnection.run_transaction/4
   (ash 3.4.44) lib/ash/changeset/changeset.ex:3498: anonymous fn/4 in Ash.Changeset.with_hooks/3
   (ash 3.4.44) lib/ash/changeset/changeset.ex:3645: anonymous fn/2 in Ash.Changeset.transaction_hooks/2
   (ash 3.4.44) lib/ash/changeset/changeset.ex:3473: Ash.Changeset.with_hooks/3
   (ash 3.4.44) lib/ash/actions/create/create.ex:260: Ash.Actions.Create.commit/3
   (ash 3.4.44) lib/ash/actions/create/create.ex:132: Ash.Actions.Create.do_run/4
   (ash 3.4.44) lib/ash/actions/create/create.ex:50: Ash.Actions.Create.run/4
   (myapp 0.1.0) lib/myapp/planner/plan_unplanned.ex:225: MyApp.Planner.PlanUnplanned.create_route/4
   (myapp 0.1.0) lib/myapp/planner/plan_unplanned.ex:213: anonymous fn/4 in MyApp.Planner.PlanUnplanned.create_route_from_response/3
   (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
   (myapp 0.1.0) lib/myapp/planner/plan_unplanned.ex:212: MyApp.Planner.PlanUnplanned.create_route_from_response/3
 stacktrace:
   (myapp 0.1.0) anonymous fn({:error, %Ash.Error.Invalid{errors: [%Ash.Error.Invalid.TenantRequired{resource: MyApp.Planner.Route, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :invalid}]}}) in MyApp.Planner.Resources.Change.IncrementDailyRoute.change/3
   (myapp 0.1.0) lib/myapp/planner/resources/change/increment_daily_route.ex:25: anonymous fn/2 in MyApp.Planner.Resources.Change.IncrementDailyRoute.change/3
   (ash 3.4.44) lib/ash/changeset/changeset.ex:3836: anonymous fn/2 in Ash.Changeset.run_before_actions/1
   (elixir 1.17.3) lib/enum.ex:4858: Enumerable.List.reduce/3
   (elixir 1.17.3) lib/enum.ex:2585: Enum.reduce_while/3
   (ash 3.4.44) lib/ash/changeset/changeset.ex:3811: Ash.Changeset.run_before_actions/1
   (ash 3.4.44) lib/ash/changeset/changeset.ex:3950: Ash.Changeset.run_around_actions/2
   (ash 3.4.44) lib/ash/changeset/changeset.ex:3500: anonymous fn/3 in Ash.Changeset.with_hooks/3
   (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1400: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
   (db_connection 2.7.0) lib/db_connection.ex:1756: DBConnection.run_transaction/4
   (ash 3.4.44) lib/ash/changeset/changeset.ex:3498: anonymous fn/4 in Ash.Changeset.with_hooks/3
   (ash 3.4.44) lib/ash/changeset/changeset.ex:3645: anonymous fn/2 in Ash.Changeset.transaction_hooks/2
   (ash 3.4.44) lib/ash/changeset/changeset.ex:3473: Ash.Changeset.with_hooks/3
   (ash 3.4.44) lib/ash/actions/create/create.ex:260: Ash.Actions.Create.commit/3
   (ash 3.4.44) lib/ash/actions/create/create.ex:132: Ash.Actions.Create.do_run/4
   (ash 3.4.44) lib/ash/actions/create/create.ex:50: Ash.Actions.Create.run/4
   (myapp 0.1.0) lib/myapp/planner/plan_unplanned.ex:225: MyApp.Planner.PlanUnplanned.create_route/4
   (myapp 0.1.0) lib/myapp/planner/plan_unplanned.ex:213: anonymous fn/4 in MyApp.Planner.PlanUnplanned.create_route_from_response/3
   (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
   (myapp 0.1.0) lib/myapp/planner/plan_unplanned.ex:212: MyApp.Planner.PlanUnplanned.create_route_from_response/3
```

**Comment by zachdaniel** [comment]
🤔 I cannot think of a way that `ash_sql` or `ash_postgres` would be at fault here TBH. Haven't been able to reproduce. Could you provide a reproduction repo or test case that shows the failure?

**Comment by DGollings** [comment]
tentant comes from inputs.context from memory

Anyway, you're likely right its not an `ash_postgres` or `ash_sql` issue

Dependabot opened a PR `Bump ash from 3.4.43 to 3.4.44`

```diff
  "ash": {:hex, :ash, "3.4.43", "5ffd63e49b71ceaf7ed15efd20cd60ec28e9c55e28fca32b24dcc690644f2656", [:mix], [{:decimal, "~> 2.0", [hex: :decimal, repo: "hexpm", optional: false]}, {:ecto, "~> 3.7", [hex: :ecto, repo: "hexpm", optional: false]}, {:ets, "~> 0.8", [hex: :ets, repo: "hexpm", optional: false]}, {:igniter, "~> 0.4", [hex: :igniter, repo: "hexpm", optional: false]}, {:jason, ">= 1.0.0", [hex: :jason, repo: "hexpm", optional: false]}, {:owl, "~> 0.11", [hex: :owl, repo: "hexpm", optional: false]}, {:picosat_elixir, "~> 0.2", [hex: :picosat_elixir, repo: "hexpm", optional: true]}, {:plug, ">= 0.0.0", [hex: :plug, repo: "hexpm", optional: true]}, {:reactor, "~> 0.9", [hex: :reactor, repo: "hexpm", optional: false]}, {:simple_sat, ">= 0.1.1 and < 1.0.0-0", [hex: :simple_sat, repo: "hexpm", optional: true]}, {:spark, ">= 2.2.29 and < 3.0.0-0", [hex: :spark, repo: "hexpm", optional: false]}, {:splode, ">= 0.2.6 and < 1.0.0-0", [hex: :splode, repo: "hexpm", optional: false]}, {:stream_data, "~> 1.0", [hex: :stream_data, repo: "hexpm", optional: false]}, {:telemetry, "~> 1.1", [hex: :telemetry, repo: "hexpm", optional: false]}], "hexpm", "2b551208878c8e91f4ac3d3b6aee037f071a90a9c1151360f2a658e3b0aadf17"},
  "ash": {:hex, :ash, "3.4.44", "10f7d0952324e4e618fd79ec6c4a4df88a087342244937c1d7807e424db05242", [:mix], [{:decimal, "~> 2.0", [hex: :decimal, repo: "hexpm", optional: false]}, {:ecto, "~> 3.7", [hex: :ecto, repo: "hexpm", optional: false]}, {:ets, "~> 0.8", [hex: :ets, repo: "hexpm", optional: false]}, {:igniter, ">= 0.4.8 and < 1.0.0-0", [hex: :igniter, repo: "hexpm", optional: false]}, {:jason, ">= 1.0.0", [hex: :jason, repo: "hexpm", optional: false]}, {:owl, "~> 0.11", [hex: :owl, repo: "hexpm", optional: false]}, {:picosat_elixir, "~> 0.2", [hex: :picosat_elixir, repo: "hexpm", optional: true]}, {:plug, ">= 0.0.0", [hex: :plug, repo: "hexpm", optional: true]}, {:reactor, "~> 0.9", [hex: :reactor, repo: "hexpm", optional: false]}, {:simple_sat, ">= 0.1.1 and < 1.0.0-0", [hex: :simple_sat, repo: "hexpm", optional: true]}, {:spark, ">= 2.2.29 and < 3.0.0-0", [hex: :spark, repo: "hexpm", optional: false]}, {:splode, ">= 0.2.6 and < 1.0.0-0", [hex: :splode, repo: "hexpm", optional: false]}, {:stream_data, "~> 1.0", [hex: :stream_data, repo: "hexpm", optional: false]}, {:telemetry, "~> 1.1", [hex: :telemetry, repo: "hexpm", optional: false]}], "hexpm", "c4d51c03b57b70ab77d782d997ab0b534415789af2fd05190e51eba2e53daee5"},
```

(also fss and swoosh, but unlikely)

**Comment by DGollings** [comment]
> test case that shows the failure?

do you have a tenant enabled test case/repo I could fork and add a test to?

**Comment by zachdaniel** [comment]
There is a multitenancy test in ash core that should work for that purpose.
